language: erlang # no C/shell language support; use least-loaded worker(s)

before_install: sudo apt-get install -y cmake

install:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - sudo make install

script: true # no tests yet
